// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {{{contract_name}}} from "../src/{{contract_name}}.sol";

/**
 * {{contract_name}} Deployment Script
 *
 * Generated by: {{TEMPLATE_NAME}} v{{TEMPLATE_VERSION}}
 * Date: {{CURRENT_DATE}}
 */
contract {{contract_name}}Script is Script {
    {{contract_name}} public voting;

    function setUp() public {}

    function run() public {
        vm.startBroadcast();

        voting = new {{contract_name}}();

        vm.stopBroadcast();
    }
}
